version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  go-app:
    image: golang:latest
    container_name: go-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${USERNAME}
      DB_PASSWORD: ${USERPASS}
      DB_NAME: ${DATABASE}

volumes:
  db_data:

